### ISSUE TITLE
Errors, when installing cvnn with pip

### ISSUE THREAD

**Issue by AntonFritsche** [NEGU93/cvnn#54]
Hi, I have a problem, when I try to install the library through pip. I have this problem on MacOS and Windows 11.

Error code:
Collecting cvnn
  Using cached cvnn-2.0.tar.gz (59 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      /private/var/folders/nf/b4thxm9s0tnf3hg53kkr70dr0000gn/T/pip-install-no6kbh75/cvnn_1cc0a018ef4b43eaa81de36b9c65aa1d/versioneer.py:421: SyntaxWarning: invalid escape sequence '\s'
        LONG_VERSION_PY['git'] = '''
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/nf/b4thxm9s0tnf3hg53kkr70dr0000gn/T/pip-install-no6kbh75/cvnn_1cc0a018ef4b43eaa81de36b9c65aa1d/setup.py", line 15, in <module>
          version=versioneer.get_version(),
                  ^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/nf/b4thxm9s0tnf3hg53kkr70dr0000gn/T/pip-install-no6kbh75/cvnn_1cc0a018ef4b43eaa81de36b9c65aa1d/versioneer.py", line 1483, in get_version
          return get_versions()["version"]
                 ^^^^^^^^^^^^^^
        File "/private/var/folders/nf/b4thxm9s0tnf3hg53kkr70dr0000gn/T/pip-install-no6kbh75/cvnn_1cc0a018ef4b43eaa81de36b9c65aa1d/versioneer.py", line 1415, in get_versions
          cfg = get_config_from_root(root)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/nf/b4thxm9s0tnf3hg53kkr70dr0000gn/T/pip-install-no6kbh75/cvnn_1cc0a018ef4b43eaa81de36b9c65aa1d/versioneer.py", line 342, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.__

**Comment by NEGU93** [comment]
Which TF version do you have? This library does not work for 2.16+ version.
